# Generated by Django 4.2.30 on 2026-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Where new enquiries (product, contact and service) are emailed. Leave empty to use the contact email above.', max_length=254),
        ),
    ]
