# Generated by Django 4.2.30 on 2026-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('featured_products', 'Featured Products'), ('testimonials', 'Testimonials'), ('why_choose_us', 'Why Choose Us'), ('categories', 'Categories'), ('brands', 'Brand Partners')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('template', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='pages_homep_order_f69a70_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_mobile', models.ImageField(blank=True, upload_to='banners/mobile/')),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(default='Learn More', max_length=100)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#FF6B35', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='pages_homep_order_2aeed8_idx')],
            },
        ),
    ]
