# Generated by Django 4.2.30 on 2026-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faqcategory_flatpage_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='ti-circle-check', help_text='Tabler icon class, e.g. ti-truck', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional one-line detail shown under the title', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service availability item',
                'verbose_name_plural': 'service availability',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='servingarea',
            name='availability',
            field=models.ManyToManyField(blank=True, help_text='Services offered in this city. Leave empty to offer every active item.', related_name='areas', to='pages.serviceavailability'),
        ),
    ]
