# Generated by Django 4.2.30 on 2026-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_seed_service_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(blank=True, default='#0f766e', max_length=7),
        ),
    ]
