# Generated by Django 6.0.5 on 2026-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_banner_mobile_category_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Black, Silver, Blue', max_length=50),
        ),
    ]
