# Generated by Django 4.2.30 on 2026-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image_alter_reviewimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#0f766e', max_length=7),
        ),
    ]
